# CMake generated Testfile for 
# Source directory: /Users/adilyoltay/Desktop/native_globe_clean
# Build directory: /Users/adilyoltay/Desktop/native_globe_clean/build_networktests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(LodConformanceTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/lod_conformance_test")
set_tests_properties(LodConformanceTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;187;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(PredictivePrefetchTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/predictive_prefetch_test")
set_tests_properties(PredictivePrefetchTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;199;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(EdgeMaskTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/edge_mask_test")
set_tests_properties(EdgeMaskTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;209;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(GlobeSystemTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/globe_system_test")
set_tests_properties(GlobeSystemTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;222;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(TileFadeTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/tile_fade_test")
set_tests_properties(TileFadeTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;232;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(CornerLodTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/corner_lod_test")
set_tests_properties(CornerLodTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;242;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(UnpopCrossfadePolicyTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/unpop_crossfade_policy_test")
set_tests_properties(UnpopCrossfadePolicyTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;252;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(TileTerrainMorphTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/tile_terrain_morph_test")
set_tests_properties(TileTerrainMorphTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;262;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(TileCacheStatsTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/tile_cache_stats_test")
set_tests_properties(TileCacheStatsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;273;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(DepthPrecisionTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/depth_precision_test")
set_tests_properties(DepthPrecisionTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;284;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(MemoryTileCacheTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/memory_tile_cache_test")
set_tests_properties(MemoryTileCacheTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;295;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(DecodedTileBlobTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/decoded_tile_blob_test")
set_tests_properties(DecodedTileBlobTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;306;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(TileDecoderBlobFastpathTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/tile_decoder_blob_fastpath_test")
set_tests_properties(TileDecoderBlobFastpathTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;319;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(TileFetcherCancelRerequestTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/tile_fetcher_cancel_rerequest_test")
set_tests_properties(TileFetcherCancelRerequestTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;331;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(TextureAtlasAllocatorTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/texture_atlas_allocator_test")
set_tests_properties(TextureAtlasAllocatorTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;342;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(FrustumExtractTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/frustum_extract_test")
set_tests_properties(FrustumExtractTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;352;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(LodLeafNonEmptyTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/lod_leaf_nonempty_test")
set_tests_properties(LodLeafNonEmptyTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;364;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(AtlasGutterUvTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/atlas_gutter_uv_test")
set_tests_properties(AtlasGutterUvTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;375;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(DemFallbackTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/dem_fallback_test")
set_tests_properties(DemFallbackTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;386;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(DemContinuityTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/dem_continuity_test")
set_tests_properties(DemContinuityTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;397;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(DemEdgeEqualizationFallbackTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/dem_edge_equalization_fallback_test")
set_tests_properties(DemEdgeEqualizationFallbackTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;412;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(MeshTemplateStitchMaskTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/mesh_template_stitch_mask_test")
set_tests_properties(MeshTemplateStitchMaskTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;424;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(SelectiveSkirtMaskTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/selective_skirt_mask_test")
set_tests_properties(SelectiveSkirtMaskTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;439;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(LodChildQuorumTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/lod_child_quorum_test")
set_tests_properties(LodChildQuorumTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;451;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(LodRefineBudgetTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/lod_refine_budget_test")
set_tests_properties(LodRefineBudgetTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;463;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(TilePyramidChildReadyTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/tile_pyramid_child_ready_test")
set_tests_properties(TilePyramidChildReadyTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;476;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(DemEffectiveLevelPolicyTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/dem_effective_level_policy_test")
set_tests_properties(DemEffectiveLevelPolicyTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;487;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(DemBatchUrlOrderTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/dem_batch_url_order_test")
set_tests_properties(DemBatchUrlOrderTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;498;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(DemGridRowOrderTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/dem_grid_row_order_test")
set_tests_properties(DemGridRowOrderTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;509;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(AdaptiveMeshSegmentsTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/adaptive_mesh_segments_test")
set_tests_properties(AdaptiveMeshSegmentsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;519;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(SeamMetricTruthTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/seam_metric_truth_test")
set_tests_properties(SeamMetricTruthTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;530;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(TileServerConnectivityTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/tile_server_connectivity_test")
set_tests_properties(TileServerConnectivityTest PROPERTIES  LABELS "network" _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;541;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
add_test(VisualParityPresetsTest "/Users/adilyoltay/Desktop/native_globe_clean/build_networktests/visual_parity_presets_test")
set_tests_properties(VisualParityPresetsTest PROPERTIES  _BACKTRACE_TRIPLES "/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;553;add_test;/Users/adilyoltay/Desktop/native_globe_clean/CMakeLists.txt;0;")
subdirs("_deps/glfw-build")
subdirs("_deps/glm-build")
