#pragma once
#include "value.h"

class GlobeApiGenerated {
public:
  virtual ~GlobeApiGenerated() = default;
  virtual Value api_AddCustomFont(const Value& a0, const Value& a1);
  virtual Value api_AddCustomLineTypes(const Value& a0);
  virtual Value api_AddIconMap(const Value& a0, const Value& a1, const Value& a2, const Value& a3);
  virtual Value api_AddImageOverlay(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5, const Value& a6, const Value& a7);
  virtual Value api_AddImageOverlayHeatmap(const Value& a0, const Value& a1);
  virtual Value api_AddLayer(const Value& a0, const Value& a1);
  virtual Value api_AddObjectBuffer(const Value& a0);
  virtual Value api_AddRaster(const Value& a0, const Value& a1);
  virtual Value api_AddTotalLayers(const Value& a0);
  virtual Value api_AddWMSOverlay(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5, const Value& a6);
  virtual Value api_Altitude();
  virtual Value api_CalcCameraGroundArea(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5, const Value& a6);
  virtual Value api_CalcLineOfSight(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_CalcSunMoon(const Value& a0, const Value& a1, const Value& a2, const Value& a3);
  virtual Value api_CamZ();
  virtual Value api_CanMoveLabelsByMouse(const Value& a0);
  virtual Value api_CanPickPoint(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5);
  virtual Value api_CanRedoEdit();
  virtual Value api_CanResetLabelsByMouse(const Value& a0);
  virtual Value api_CanUndoEdit();
  virtual Value api_CancelEditObj();
  virtual Value api_CancelScreenWidthAndMinMaxLOD();
  virtual Value api_CancelVisibilityAnalysis(const Value& a0);
  virtual Value api_ChangeImageOverlayURL(const Value& a0, const Value& a1);
  virtual Value api_ChangeWMSOverlayURL(const Value& a0, const Value& a1);
  virtual Value api_ClearMouseEvents();
  virtual Value api_CloseOverviewFromPanel(const Value& a0);
  virtual Value api_ConvertAngleValueToDegree(const Value& a0);
  virtual Value api_ConvertColorStringToFloat(const Value& a0, const Value& a1);
  virtual Value api_ConvertDistanceValueToMeter(const Value& a0);
  virtual Value api_Create3dDashedLineShaderLocations(const Value& a0);
  virtual Value api_Create3dDashedLineShaderProgram();
  virtual Value api_Create3dShaderLocations(const Value& a0);
  virtual Value api_Create3dShaderProgram();
  virtual Value api_CreateBuffer();
  virtual Value api_CreateCircleShaderLocations(const Value& a0);
  virtual Value api_CreateCircleShaderProgram();
  virtual Value api_CreateIconShaderLocations(const Value& a0);
  virtual Value api_CreateIconShaderProgram();
  virtual Value api_CreateIconVertexBuffer(const Value& a0, const Value& a1);
  virtual Value api_CreateModel(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5, const Value& a6, const Value& a7, const Value& a8, const Value& a9, const Value& a10);
  virtual Value api_CreateObjectBuffer(const Value& a0, const Value& a1);
  virtual Value api_CreateTexture(const Value& a0, const Value& a1);
  virtual Value api_DMSToGeo(const Value& a0);
  virtual Value api_DeleteAllObjectBuffers();
  virtual Value api_DeleteAllPlugins();
  virtual Value api_DeleteIconMap(const Value& a0);
  virtual Value api_DeleteIconMaps();
  virtual Value api_DeleteImageOverlay(const Value& a0, const Value& a1);
  virtual Value api_DeleteLayer(const Value& a0);
  virtual Value api_DeleteLayers();
  virtual Value api_DeleteObjectBufferById(const Value& a0);
  virtual Value api_DeleteObjectBufferByIndex(const Value& a0);
  virtual Value api_DeleteRaster(const Value& a0);
  virtual Value api_DeleteRasters();
  virtual Value api_DeleteShaderParams(const Value& a0);
  virtual Value api_DeleteWMSOverlay(const Value& a0);
  virtual Value api_Draw3dDashedLine(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5, const Value& a6, const Value& a7, const Value& a8, const Value& a9, const Value& a10);
  virtual Value api_Draw3dDashedLineLoop(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5, const Value& a6, const Value& a7, const Value& a8, const Value& a9, const Value& a10);
  virtual Value api_Draw3dDashedLineLoopCurModelProjection(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_Draw3dDashedLineStrip(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5, const Value& a6, const Value& a7, const Value& a8, const Value& a9, const Value& a10);
  virtual Value api_Draw3dDashedLineStripCurModelProjection(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_Draw3dLine(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5, const Value& a6, const Value& a7, const Value& a8);
  virtual Value api_Draw3dLineCurModelProjection(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_Draw3dLineLoop(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5, const Value& a6, const Value& a7, const Value& a8);
  virtual Value api_Draw3dLineLoopCurModelProjection(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_Draw3dLineStrip(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5, const Value& a6, const Value& a7, const Value& a8);
  virtual Value api_Draw3dLineStripCurModelProjection(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_Draw3dPolygon(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5, const Value& a6, const Value& a7, const Value& a8, const Value& a9);
  virtual Value api_Draw3dPolygonCurModelProjection(const Value& a0, const Value& a1, const Value& a2, const Value& a3);
  virtual Value api_Draw3dPolygonStrip(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5, const Value& a6, const Value& a7, const Value& a8, const Value& a9);
  virtual Value api_Draw3dPolygonStripCurModelProjection(const Value& a0, const Value& a1, const Value& a2, const Value& a3);
  virtual Value api_DrawBaseGlobeColor(const Value& a0);
  virtual Value api_DrawCircle(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5, const Value& a6, const Value& a7, const Value& a8);
  virtual Value api_DrawCircleCurModelProjection(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_DrawContextText(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5, const Value& a6, const Value& a7);
  virtual Value api_DrawContextTextInScreen(const Value& a0, const Value& a1, const Value& a2, const Value& a3);
  virtual Value api_DrawContextTextMultiLine(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5, const Value& a6, const Value& a7);
  virtual Value api_DrawIcon(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5, const Value& a6);
  virtual Value api_DrawIconCurProjection(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_GetDrawCommands();
  virtual Value api_ClearDrawCommands();
  virtual Value api_EditCallbackChanged();
  virtual Value api_EditCallbackCreator();
  virtual Value api_DispatchEvent(const Value& a0, const Value& a1);
  virtual Value api_TriggerCallback(const Value& a0, const Value& a1);
  virtual Value api_ExchangeObjectBuffer(const Value& a0, const Value& a1);
  virtual Value api_FPS();
  virtual Value api_Fill3dIndexBuffer(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_Fill3dVertexBuffer(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_Fill3dVertexBufferByGeoArr(const Value& a0, const Value& a1, const Value& a2, const Value& a3);
  virtual Value api_Fill3dVertexBufferByGeoArr_SameZ(const Value& a0, const Value& a1, const Value& a2, const Value& a3);
  virtual Value api_FillIndexBufferData(const Value& a0, const Value& a1);
  virtual Value api_FillVertexBufferData(const Value& a0, const Value& a1);
  virtual Value api_FindObjectBufferById(const Value& a0);
  virtual Value api_FindProfile(const Value& a0, const Value& a1, const Value& a2, const Value& a3);
  virtual Value api_FlyToPoint(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4);
  virtual Value api_FlyToPointDirect(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4);
  virtual Value api_FlyToRegion(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4);
  virtual Value api_FlyToRegionDirect(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4);
  virtual Value api_FollowGroundMaxVertex(const Value& a0);
  virtual Value api_FreeFontDrawer();
  virtual Value api_FreeModelDrawer();
  virtual Value api_GeoJSONToObjectArrData(const Value& a0);
  virtual Value api_GeoRefToGeo(const Value& a0);
  virtual Value api_GeoToDMS(const Value& a0, const Value& a1);
  virtual Value api_GeoToGeoRef(const Value& a0, const Value& a1);
  virtual Value api_GeoToMGRS(const Value& a0);
  virtual Value api_GeoToUTM(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_GeometryCalculationTypes();
  virtual Value api_GeometryTypes();
  virtual Value api_Get3DPoint(const Value& a0, const Value& a1, const Value& a2, const Value& a3);
  virtual Value api_Get3DPoints(const Value& a0, const Value& a1);
  virtual Value api_Get3DPointsByGeoArr(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_Get3DPointsByGeoArr_SameZ(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_GetAllPluginsId();
  virtual Value api_GetCameraDist();
  virtual Value api_GetCartesian3DPoint(const Value& a0, const Value& a1, const Value& a2, const Value& a3);
  virtual Value api_GetCartesian3DPoints(const Value& a0, const Value& a1);
  virtual Value api_GetCartesian3DPointsByGeoArr(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_GetCartesian3DPointsByGeoArr_SameZ(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_GetCartesian3DPointsDeneme(const Value& a0);
  virtual Value api_GetContextTextWidth(const Value& a0);
  virtual Value api_GetCurrentGeometry();
  virtual Value api_GetCurrentLOD();
  virtual Value api_GetCurrentLODWithDecimal();
  virtual Value api_GetCurrentLookInfo();
  virtual Value api_GetCurrentMinLOD();
  virtual Value api_GetCurrentScale();
  virtual Value api_GetCurrentWorldLimit();
  virtual Value api_GetCurrentWorldWH();
  virtual Value api_GetDefaultCircleIcon();
  virtual Value api_GetDefaultClusterStyle(const Value& a0);
  virtual Value api_GetDefaultCompositeLayerStyle();
  virtual Value api_GetDefaultHeightIcon();
  virtual Value api_GetDefaultLayerStyle();
  virtual Value api_GetDefaultLayerStyleNoIcon();
  virtual Value api_GetDefaultMarkIcon();
  virtual Value api_GetDefaultMaxZIcon();
  virtual Value api_GetDefaultMinZIcon();
  virtual Value api_GetDefaultMoveIcon();
  virtual Value api_GetDefaultNotFoundIcon();
  virtual Value api_GetDefaultRotateIcon();
  virtual Value api_GetDefaultScaleIcon();
  virtual Value api_GetDefaultStyle();
  virtual Value api_GetDefaultStyleNoIcon();
  virtual Value api_GetDirectPosNatural();
  virtual Value api_GetDrawedTilesXYZ();
  virtual Value api_GetEditCallback();
  virtual Value api_GetEditingObj();
  virtual Value api_GetFlashPeriod();
  virtual Value api_GetFontStyle();
  virtual Value api_GetGL();
  virtual Value api_GetGLColor(const Value& a0, const Value& a1);
  virtual Value api_GetGeoFromScreenPoint(const Value& a0, const Value& a1);
  virtual Value api_GetGeoJSONBBOX(const Value& a0);
  virtual Value api_GetGeometryCalculationForFlat();
  virtual Value api_GetGridPolygon(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_GetIconMapNameList();
  virtual Value api_GetImageOverlay(const Value& a0);
  virtual Value api_GetImageOverlayBBOX(const Value& a0, const Value& a1);
  virtual Value api_GetLang();
  virtual Value api_GetLayer(const Value& a0);
  virtual Value api_GetLayerById(const Value& a0);
  virtual Value api_GetLayerLimitsOfLoadedObjects(const Value& a0);
  virtual Value api_GetLayerOn(const Value& a0);
  virtual Value api_GetLayerStyle(const Value& a0);
  virtual Value api_GetMagneticNorthAngle(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_GetMainJSVersion();
  virtual Value api_GetMercator2DPoint(const Value& a0, const Value& a1);
  virtual Value api_GetMercator3DPoint(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_GetMercator3DPoints(const Value& a0);
  virtual Value api_GetMercator3DPointsByGeoArr(const Value& a0, const Value& a1);
  virtual Value api_GetMercator3DPointsByGeoArr_SameZ(const Value& a0, const Value& a1);
  virtual Value api_GetMercatorPoint(const Value& a0, const Value& a1);
  virtual Value api_GetMouseCursor();
  virtual Value api_GetMouseDeg();
  virtual Value api_GetMouseEvent(const Value& a0);
  virtual Value api_GetMousePos();
  virtual Value api_GetNavigationSpeed();
  virtual Value api_GetNewLayerId();
  virtual Value api_GetNewObjectBufferId();
  virtual Value api_GetNewRasterId();
  virtual Value api_GetObjectBuffer(const Value& a0);
  virtual Value api_GetObjectLimit(const Value& a0);
  virtual Value api_GetPlugin(const Value& a0);
  virtual Value api_GetProjMatrixAtMode2d();
  virtual Value api_GetQueryBoxSize();
  virtual Value api_GetRaster(const Value& a0);
  virtual Value api_GetRasterById(const Value& a0);
  virtual Value api_GetRasterGrayScaleMode();
  virtual Value api_GetRasterONOFF(const Value& a0);
  virtual Value api_GetRasterONOFFById(const Value& a0);
  virtual Value api_GetRasterOpacity(const Value& a0);
  virtual Value api_GetRasterizeStyle();
  virtual Value api_GetReductionBoxSize();
  virtual Value api_GetReductionPeriod();
  virtual Value api_GetScaleBarPos();
  virtual Value api_GetScreenAsDegree(const Value& a0, const Value& a1);
  virtual Value api_GetScreenCenterAsDegree();
  virtual Value api_GetScreenPointFromGeo(const Value& a0, const Value& a1);
  virtual Value api_GetShapeBitmap(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5, const Value& a6);
  virtual Value api_GetShapeCount();
  virtual Value api_GetShapeTypes();
  virtual Value api_GetTotalLayersAsJSON();
  virtual Value api_GetUTMZone(const Value& a0, const Value& a1);
  virtual Value api_GetZ(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5, const Value& a6, const Value& a7);
  virtual Value api_GetZClient(const Value& a0, const Value& a1);
  virtual Value api_GetZScale();
  virtual Value api_GlobeFree();
  virtual Value api_GlobeIsValid();
  virtual Value api_GlobeVersion();
  virtual Value api_GoToNextPosition();
  virtual Value api_GoToPreviousPosition();
  virtual Value api_IsNextPositionAvailable();
  virtual Value api_IsPreviousPositionAvailable();
  virtual Value api_IsScreenMoving();
  virtual Value api_LAYER_TYPE_CS_OBJECT_ARRAY();
  virtual Value api_LAYER_TYPE_MVT_XYZ();
  virtual Value api_LAYER_TYPE_OGC_WFS();
  virtual Value api_LayerCount();
  virtual Value api_LayerObjectToJSON(const Value& a0);
  virtual Value api_LayerStyleChanged(const Value& a0);
  virtual Value api_LeaveCamera(const Value& a0);
  virtual Value api_LineOfSight(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5, const Value& a6, const Value& a7, const Value& a8);
  virtual Value api_LoadVectorLayerWhileScreenIsMoving(const Value& a0);
  virtual Value api_MGRSToGeo(const Value& a0);
  virtual Value api_NorthAngleDeg();
  virtual Value api_Object3DShapeTypes();
  virtual Value api_ObjectBufferCount();
  virtual Value api_ObjectCreator(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_ObjectToPolygon(const Value& a0);
  virtual Value api_ObjectTypes();
  virtual Value api_OnScaleBarClick(const Value& a0);
  virtual Value api_OrbitDistance();
  virtual Value api_QueryByBBox(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_QueryByGeometry(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_QueryByObject_InsideData(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_QueryByObject_InsideGlobe(const Value& a0, const Value& a1);
  virtual Value api_QueryByObject_InsideSelectionSet(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_QueryByObject_OverlapData(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_QueryByObject_OverlapGlobe(const Value& a0, const Value& a1);
  virtual Value api_QueryByObject_OverlapSelectionSet(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_QueryByScreen(const Value& a0, const Value& a1);
  virtual Value api_RasterCount();
  virtual Value api_ReTryAtMeshTimeout(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_ReTryAtRasterTimeout(const Value& a0, const Value& a1);
  virtual Value api_ReTryAtVectorLayerTimeout(const Value& a0, const Value& a1);
  virtual Value api_RedoEdit();
  virtual Value api_RegisterPlugin(const Value& a0, const Value& a1);
  virtual Value api_ReloadLayer(const Value& a0);
  virtual Value api_ResetBlendFunction(const Value& a0);
  virtual Value api_ResetDepthTest2D();
  virtual Value api_ResetDepthTest3D();
  virtual Value api_ResetMaxFPS();
  virtual Value api_ResetStencilFunction(const Value& a0);
  virtual Value api_ScrH();
  virtual Value api_ScrW();
  virtual Value api_Set2DMode(const Value& a0);
  virtual Value api_Set2dPosition(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_Set2dProjection(const Value& a0);
  virtual Value api_Set2dScale(const Value& a0, const Value& a1);
  virtual Value api_Set3dDashedLineDashGapSize(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_Set3dModelProjection(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_Set3dPosition(const Value& a0, const Value& a1);
  virtual Value api_SetArrowKeysNavSpeed(const Value& a0);
  virtual Value api_SetCameraCallBack(const Value& a0);
  virtual Value api_SetCameraPos(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5);
  virtual Value api_SetCameraPosChanged(const Value& a0, const Value& a1);
  virtual Value api_SetCircleParams(const Value& a0, const Value& a1);
  virtual Value api_SetCompass(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_SetCompositeLayerVisibility(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_SetContinuousRotation(const Value& a0);
  virtual Value api_SetDirectPosNatural(const Value& a0);
  virtual Value api_SetEditingObjParams(const Value& a0);
  virtual Value api_SetExtraCot(const Value& a0);
  virtual Value api_SetExtraDeg(const Value& a0);
  virtual Value api_SetFlashPeriod(const Value& a0);
  virtual Value api_SetFog(const Value& a0);
  virtual Value api_SetGeometry(const Value& a0);
  virtual Value api_SetGlobalRasterBrightness(const Value& a0);
  virtual Value api_SetGlobalRasterColor(const Value& a0);
  virtual Value api_SetGlobalRasterizeBrightness(const Value& a0);
  virtual Value api_SetGlobalSymbolAndTextScale(const Value& a0, const Value& a1);
  virtual Value api_SetGlobeBrightness(const Value& a0);
  virtual Value api_SetGlobeColor(const Value& a0);
  virtual Value api_SetImageOverlayColor(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_SetLang(const Value& a0);
  virtual Value api_SetLayerCacheSize(const Value& a0);
  virtual Value api_SetLayerOn(const Value& a0, const Value& a1);
  virtual Value api_SetLayerOpacity(const Value& a0, const Value& a1);
  virtual Value api_SetLayerRuleVisibility(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_SetLockNorth(const Value& a0);
  virtual Value api_SetMVTLayerPadding(const Value& a0);
  virtual Value api_SetMaxFPS(const Value& a0);
  virtual Value api_SetMaxNavigationDist(const Value& a0);
  virtual Value api_SetMaxNavigationLOD(const Value& a0);
  virtual Value api_SetMaxOpenRasterCount(const Value& a0);
  virtual Value api_SetMeshCacheSize(const Value& a0);
  virtual Value api_SetMidTurnAnimation(const Value& a0);
  virtual Value api_SetMilSymbol(const Value& a0);
  virtual Value api_SetMinNavigationDist(const Value& a0);
  virtual Value api_SetMinNavigationLOD(const Value& a0);
  virtual Value api_SetModelWireFrameMode(const Value& a0);
  virtual Value api_SetMonitorDPI(const Value& a0);
  virtual Value api_SetMouseCursor(const Value& a0);
  virtual Value api_SetMouseEvents(const Value& a0, const Value& a1);
  virtual Value api_SetMouseWheelDirection(const Value& a0);
  virtual Value api_SetMouseWheelMode(const Value& a0);
  virtual Value api_SetZoomWheelInDist(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4);
  virtual Value api_SetZoomWheelOutDist(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4);
  virtual Value api_SetNavigationDist(const Value& a0);
  virtual Value api_SetNavigationLOD(const Value& a0);
  virtual Value api_SetNavigationSpeed(const Value& a0);
  virtual Value api_SetNorthAngle(const Value& a0);
  virtual Value api_SetObjectHint(const Value& a0, const Value& a1);
  virtual Value api_SetOverview(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_SetProjectionLimit(const Value& a0, const Value& a1, const Value& a2, const Value& a3);
  virtual Value api_SetQueryBoxSize(const Value& a0);
  virtual Value api_SetRasterCacheSize(const Value& a0);
  virtual Value api_SetRasterGrayScaleMode(const Value& a0);
  virtual Value api_SetRasterLodPriority();
  virtual Value api_SetRasterONOFF(const Value& a0, const Value& a1);
  virtual Value api_SetRasterOpacity(const Value& a0, const Value& a1);
  virtual Value api_SetRasterZIndex(const Value& a0, const Value& a1);
  virtual Value api_SetRasterService(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_SetRasterTimeOut(const Value& a0);
  virtual Value api_GetRasterZIndex(const Value& a0);
  virtual Value api_SetReductionBoxSize(const Value& a0);
  virtual Value api_SetReductionPeriod(const Value& a0);
  virtual Value api_SetRegionSelect(const Value& a0, const Value& a1, const Value& a2, const Value& a3);
  virtual Value api_SetScaleBar(const Value& a0, const Value& a1);
  virtual Value api_SetScalebarImage(const Value& a0);
  virtual Value api_SetScreenWidth(const Value& a0, const Value& a1);
  virtual Value api_SetShaderColor(const Value& a0, const Value& a1);
  virtual Value api_SetShaderOpacity(const Value& a0, const Value& a1);
  virtual Value api_SetSpaceColor(const Value& a0);
  virtual Value api_SetStatusBarCallBack(const Value& a0);
  virtual Value api_SetTexture(const Value& a0, const Value& a1);
  virtual Value api_SetTiltAngle(const Value& a0);
  virtual Value api_SetUndoBuffersChangedEvent(const Value& a0);
  virtual Value api_SetUserObjHighlightProperties(const Value& a0, const Value& a1, const Value& a2, const Value& a3, const Value& a4, const Value& a5);
  virtual Value api_SetVectorLayerTimeOut(const Value& a0);
  virtual Value api_SetWMSOverlayColor(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_SetWireFrameMode(const Value& a0);
  virtual Value api_SetZScale(const Value& a0);
  virtual Value api_ShapeTypes();
  virtual Value api_ShowCompass(const Value& a0);
  virtual Value api_ShowDebug(const Value& a0);
  virtual Value api_ShowGrid(const Value& a0, const Value& a1, const Value& a2);
  virtual Value api_ShowOverview(const Value& a0);
  virtual Value api_ShowScaleBar(const Value& a0);
  virtual Value api_ShowStatusBar(const Value& a0);
  virtual Value api_StartEditObj(const Value& a0, const Value& a1, const Value& a2, const Value& a3);
  virtual Value api_StopEditObj(const Value& a0, const Value& a1);
  virtual Value api_TurnToNorth(const Value& a0);
  virtual Value api_TurnToNorthDirect(const Value& a0);
  virtual Value api_UTMToGeo(const Value& a0, const Value& a1, const Value& a2, const Value& a3);
  virtual Value api_UnRegisterPlugin(const Value& a0);
  virtual Value api_UndoEdit();
  virtual Value api_UpdateLayer(const Value& a0, const Value& a1);
  virtual Value api_UseProgram(const Value& a0);
  virtual Value api_UseTextureBuffer(const Value& a0);
  virtual Value api_VisibilityAnalysis(const Value& a0, const Value& a1);
  virtual Value api_WriteDebug(const Value& a0);
  virtual Value api_ZoomToLOD(const Value& a0);
  virtual Value api_ZoomToPaperScale(const Value& a0);
};
